language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5-dev"
  - "nightly"

script:
  - python setup.py test
  - if [[ "$TRAVIS_PYTHON_VERSION" != "nightly" ]]; then coverage run setup.py test ; fi

notifications:
  email: false
before_install:
  - pip install codecov
after_success:
  - codecov
